### ISSUE TITLE
Problem installing... Step 4.- Install Regrader

### ISSUE THREAD

**Issue by calavera2013** [fushar/regrader#33]
Hello, 

I'm trying to install regrader but I have problems with the step 4.
#### 4. Install Regrader

Open Regrader in your browser, and perform the installation steps as instructed. If at any step the system cannot install at some specified directories, please add write permission on them.

I've installed php5 and apache2, but when I put in my browser localhost/regrader-develop only appears  the code of php file, but doesn't run the anything.

Could you help me?? Thanks a lot.

**Comment by koushik0810** [comment]
Even i too getting the same problem.
Could anyone explain me how to install step no4, please

**Comment by fushar** [comment]
Hi @koushik0810 -- first you have to make sure you have a running PHP installation (this is not related to regrader). As I said before, there are many resources on the internet (google "apache does not execute php" for example).

**Comment by koushik0810** [comment]
yep i am having that bt i am facing problem during installation. i google about it, but i am not getting the clear view. 
 could you please explain me clearly

**Comment by fushar** [comment]
Dear @koushik0810,

Just want to check -- have you resolved the problem?

Thanks!

**Comment by koushik0810** [comment]
No still am facing that problem only

**Comment by fushar** [comment]
Some articles that might help:

- http://www.mograblog.com/2011/02/what-to-do-when-apache-shows-your-php.html
- http://stackoverflow.com/questions/3555681/why-are-my-php-files-showing-as-plain-text
