### ISSUE TITLE
Error while compile moe

### ISSUE THREAD

**Issue by nielswiles** [fushar/regrader#43]
Hi,
When I compile moe, this error is appeared:
a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
a2x: ERROR: "xmllint" --nonet --noout --valid "/regrader/moe/obj/isolate/isolate.1.xml" returned non-zero exit status 127
make: *** [obj/isolate/isolate.1] Error 1
How can I fix it?

**Comment by fushar** [comment]
(conversation closed in emails)
