### ISSUE TITLE
Source code not compiled yet-   Always....

### ISSUE THREAD

**Issue by AlonSerrano** [fushar/regrader#45]
![image](https://cloud.githubusercontent.com/assets/10080082/5310749/a6d689f2-7bfe-11e4-9958-0e46d2a9f25a.png)
I have always the same problem!!! i cant compile the code!!! 
Help!!! please

**Comment by FitrahRama** [comment]
![image](https://cloud.githubusercontent.com/assets/10583542/6349434/f580faee-bc5c-11e4-9214-5f2d4baa5c6a.png)

Hi @AlonSerrano and @fushar, 
I havsame problem. "Source code not compiled yet".
then i try to run run_grader.sh, but it doesn't work as well.
Help, please..

**Comment by fushar** [comment]
Closing because of no responses.
