### ISSUE TITLE
Grading didn't work

### ISSUE THREAD

**Issue by HieronyM** [fushar/regrader#48]
Hello @fushar,
I try installing your application into my Centos 6.4
The application going right in Compiling the code ( test for C and C++), but
something wrong in Grading the Code.
Problem :
 - If I didn't upload any TestCase for the problem, all of the submission to the problem got Accepted.
 - If I uploaded any Testcase, all of the submission to the problem got Wrong Answer Verdict. The Answer should be Accepted (I Have upload code that print anything in the .out file ).

When I cek the submission folder, I found that it created 2 folder (judging & source).

![issue1](https://cloud.githubusercontent.com/assets/8222055/5954100/8f1bd0d6-a7c5-11e4-9afd-5544fd653ad3.png)

Compile source contain this files, and I think it ok.

![issue2](https://cloud.githubusercontent.com/assets/8222055/5954125/cbeedf08-a7c5-11e4-8daa-78612fe9f7f5.png)

But when I open the Grading folder, there no files there. And I think this is the problem.

![issue3](https://cloud.githubusercontent.com/assets/8222055/5954139/00db1fce-a7c6-11e4-8cd1-301dffde2233.png)

Wish you can help me out of this, because the deadline for our Local competition is close.
For your attention, I say thanks.

**Comment by fushar** [comment]
Hi @HieronyM,

The grading folder being empty is normal -- all temporary files are deleted after grading.

For the WA verdict, please check, do your test case outputs contain newlines? (This is mentioned in the FAQ section actually.)

**Comment by HieronyM** [comment]
for the Testcase that I use is here

.out File : http://pastebin.com/Z1ZzTv38
And I'm sure it doesn't contain newline.

FYI, this is my .in File : http://pastebin.com/pR4JDvEW

And this is My Code : http://pastebin.com/ifXJvvea

**Comment by fushar** [comment]
(Issue resolved off-line.)

Summary:

Moe was not built for unknown reasons. After building moe manually, the problem was resolved.
