### ISSUE TITLE
Error when compile, No such file or directory

### ISSUE THREAD

**Issue by syamcode** [fushar/regrader#50]
Hi @fushar , 
when i compiling the code, why this error always appear
![captuare](https://cloud.githubusercontent.com/assets/9907952/6821818/8168824a-d30d-11e4-8e56-41db7e911a44.PNG)
here is the full of error message,
[2015-03-25 16:22:20] Grader started.
[2015-03-25 16:22:20] Waiting for new submission...
[2015-03-25 16:25:00] Found new submission!
                      Submission     : 13
                      User           : syamcode (Muhamad Hisyam)
                      Contest        : 1 (Tes Coding Competition)
                      Problem        : TL (Tulis Lagi)
                      Language       : C
[2015-03-25 16:25:02] Compile status : 0
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  file_get_contents(secret-8f4b3123e46ddd5b85b0e57b49e598d4/13/judging/2/result): failed to open stream: No such file or directory</p>
<p>Filename: controllers/grader.php</p>
<p>Line Number: 276</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  file_get_contents(secret-8f4b3123e46ddd5b85b0e57b49e598d4/13/judging/2/checker_op): failed to open stream: No such file or directory</p>
<p>Filename: controllers/grader.php</p>
<p>Line Number: 310</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  unlink(secret-8f4b3123e46ddd5b85b0e57b49e598d4/13/judging/2/checker_op): No such file or directory</p>
<p>Filename: controllers/grader.php</p>
<p>Line Number: 318</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined index: time-wall</p>
<p>Filename: controllers/grader.php</p>
<p>Line Number: 333</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined index: mem</p>
<p>Filename: controllers/grader.php</p>
<p>Line Number: 334</p>

</div>[2015-03-25 16:25:02] TC 2 verdict   : Wrong Answer (0 ms, 0 KB)
<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  unlink(secret-8f4b3123e46ddd5b85b0e57b49e598d4/13/judging/2/error): No such file or directory</p>
<p>Filename: controllers/grader.php</p>
<p>Line Number: 342</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  unlink(secret-8f4b3123e46ddd5b85b0e57b49e598d4/13/judging/2/result): No such file or directory</p>
<p>Filename: controllers/grader.php</p>
<p>Line Number: 343</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  unlink(secret-8f4b3123e46ddd5b85b0e57b49e598d4/13/judging/2/2.out): No such file or directory</p>
<p>Filename: controllers/grader.php</p>
<p>Line Number: 344</p>

</div>[2015-03-25 16:25:02] Final verdict  : Wrong Answer
[2015-03-25 16:25:02] Waiting for new submission...

thanks for your attention,

**Comment by fushar** [comment]
Hey @syamcode,

Does this file exist and executable: moe/obj/box/box?

**Comment by syamcode** [comment]
do you mean moe/box ? yes, its exist and executable

**Comment by fushar** [comment]
No, you must have moe/obj/box/box. If not, then Moe was not built correctly.

Try rebuilding it. Inside moe directory, run

`./configure`

and then

`make`

**Comment by syamcode** [comment]
thanks @fushar , now the error message is not shown, 
but when i try to submit a submission, the verdict is always Runtime Error..
i try to make a simple problem, this is my code
#include <stdio.h>

int main(void) {
	int n;
	scanf("%d",&n);
	printf("%d\n",n);
	return 0;
}

input : 100
output : 100\n
i have upload my test case with .in and .out extension.

**Comment by fushar** [comment]
Have you set up the correct compiler path etc in Manage->Languages?

**Comment by syamcode** [comment]
i use default compiler path, and i think my compiler path is correct

**Comment by syamcode** [comment]
Solved, i have wrong permission in the moe directory thanks for your help @fushar
