### ISSUE TITLE
Installation Problem ( linux mint 15 olivia 64bit )

### ISSUE THREAD

**Issue by ShipuAhamed** [fushar/regrader#6]
i am using linux mint 15 olivia........64 bit
when i install regrader ............
![screenshot](https://cloud.githubusercontent.com/assets/4118421/2624762/39986e74-bd62-11e3-977c-031f2b13814b.png)

before, installing, i edit this for linux 64 bit os  moe/default.cfg. Uncomment these lines: # Set("CONFIG_BOX_KERNEL_AMD64" => 1); # Set("CONFIG_BOX_USER_AMD64" => 1);

bootstrap css not working .......... my permission status is..........
![screenshot-1](https://cloud.githubusercontent.com/assets/4118421/2624776/117494d0-bd63-11e3-9ee7-162c998b6eb4.png)

how can i fixed it...........

**Comment by fushar** [comment]
This should work using the latest moe. Please try using the latest version of Regrader.
