### ISSUE TITLE
Unable to load Indonesian language

### ISSUE THREAD

**Issue by saifulwebid** [fushar/regrader#70]
I edited `application/config/config.php` file on line 73 to change the display language to Indonesian.

When I still log in, I could see the interface properly. But after I log out and I try to log in again, this error showed up: "Unable to load the requested language file: language/indonesian/form_validation_lang.php".

![screenshot 2016-03-23 05 02 04](https://cloud.githubusercontent.com/assets/1644410/13969339/cfb31508-f0b4-11e5-97e2-a6a10ea465dd.png)

**Comment by fushar** [comment]
@saifulwebid -- thanks for the report! I just fixed it, please download/clone/build the latest version (2.2.1) :)
