### ISSUE TITLE
bootsrapt doesn't work

### ISSUE THREAD

**Issue by ecojuntak** [fushar/regrader#72]
I have finished install the Regrader, but when I try load the web  the styling is not work.
How can I solve it?
![screenshot from 2016-04-07 22 16 05](https://cloud.githubusercontent.com/assets/9149602/14356957/fabd208c-fd10-11e5-9267-97d55d7dda30.png)

**Comment by fushar** [comment]
Hi @ecojuntak, 

Try viewing the source. You should see the following on top of the file:

```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	
	<link type="text/css" href="http://regrader.local/assets/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
	<link type="text/css" href="http://regrader.local/assets/css/style.css" rel="stylesheet"/>

	
	<link rel="shortcut icon" href="http://regrader.local/files/favicon.ico">
	<script type="text/javascript" src="http://regrader.local/assets/vendor/jquery/dist/jquery.min.js"></script>
	<script type="text/javascript" src="http://regrader.local/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="http://regrader.local/assets/js/clocks.js"></script>
```

Try clicking on the `.css` files and see if they point to existing files?

**Comment by ecojuntak** [comment]
1.I can find the vendor folder on assets folder.
![screenshot from 2016-04-08 07 58 34](https://cloud.githubusercontent.com/assets/9149602/14371235/d523a158-fd5f-11e5-8d67-3f177c5bb4fa.png)

2.What file .css do you mean?

**Comment by fushar** [comment]
If you can't find `vendor` folder that means you didn't install it correctly. Are you sure you followed `README`? Are you sure you download Regrader from https://github.com/fushar/regrader/releases/download/v2.2.1/regrader-v2.2.1.tar.gz?

**Comment by ecojuntak** [comment]
I have solved it.
This is the way i solved it. First I download the master package. Then I download the version2.2.1 package. Then i extract the packages and i merge all the files.
After it I follow all the step written README..

But now the next problems is to set the compile command. How to set compile command C and C++ language??

**Comment by fushar** [comment]
That's not how you would do it, although it may work. If you really want to install from source, you need to follow this: https://github.com/fushar/regrader#contributing.

Could you open a new issue for compile command? Which part didn't you understand?
