### ISSUE TITLE
Failed to add testcase

### ISSUE THREAD

**Issue by RxFroScarletD** [fushar/regrader#74]
Hello, i want to add testcase in on a problem. but appear alert "The upload path does not appear to be valid.". Thanks :)

**Comment by fushar** [comment]
Can you attach screenshots please?

**Comment by RxFroScarletD** [comment]
here: [http://imgur.com/YF0gJUg](url)

**Comment by RxFroScarletD** [comment]
here: http://imgur.com/YF0gJUg

**Comment by fushar** [comment]
Can you confirm that you have several folders called `secret-<some random string>` inside your regrader installation?

**Comment by RxFroScarletD** [comment]
My Condition:
1. 3 folders secret-<random string> was out of my regrader installation folder.
2. then, i just copy-paste those folder to regrader folder, but alert still appear.
3. i am trying to reinstall regrader, but condition back to step 1.



PS: Actually after installation i have some error warning.
here my screenshot: http://imgur.com/a/R48ku

**Comment by ecojuntak** [comment]
@RxFroScarletD i try to reinstall regrader, before reinstall I switch the php version 7.1 to 5.6

I'm not sure the php version cause the error, but it works for me
